/**
 * Machine-readable domain error codes returned in every API error response.
 *
 * Format: <DOMAIN>_<DESCRIPTION>
 *
 * Auth codes (AUTH_*)          – authentication and authorization failures
 * Validation codes (VAL_*)     – input / schema validation failures
 * Resource codes (RES_*)       – entity lookup / conflict failures
 * Business-rule codes (BIZ_*)  – domain rule violations
 * System codes (SYS_*)         – internal / infrastructure errors
 */
export enum ErrorCode {
  // ── Auth ──────────────────────────────────────────────────────────────────
  AUTH_MISSING_TOKEN = 'AUTH_MISSING_TOKEN',
  AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN',
  AUTH_EXPIRED_TOKEN = 'AUTH_EXPIRED_TOKEN',
  AUTH_REFRESH_TOKEN_INVALID = 'AUTH_REFRESH_TOKEN_INVALID',
  AUTH_REFRESH_TOKEN_EXPIRED = 'AUTH_REFRESH_TOKEN_EXPIRED',
  AUTH_INSUFFICIENT_PERMISSIONS = 'AUTH_INSUFFICIENT_PERMISSIONS',
  AUTH_ACCOUNT_NOT_VERIFIED = 'AUTH_ACCOUNT_NOT_VERIFIED',
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_DISABLED = 'AUTH_ACCOUNT_DISABLED',
  AUTH_CERTIFICATE_DOWNLOAD_TOKEN_INVALID = 'AUTH_CERTIFICATE_DOWNLOAD_TOKEN_INVALID',
  AUTH_CERTIFICATE_DOWNLOAD_TOKEN_EXPIRED = 'AUTH_CERTIFICATE_DOWNLOAD_TOKEN_EXPIRED',
  AUTH_CERTIFICATE_DOWNLOAD_TOKEN_MISMATCH = 'AUTH_CERTIFICATE_DOWNLOAD_TOKEN_MISMATCH',

  // ── Validation ────────────────────────────────────────────────────────────
  VAL_INVALID_INPUT = 'VAL_INVALID_INPUT',
  VAL_MISSING_FIELD = 'VAL_MISSING_FIELD',
  VAL_INVALID_FORMAT = 'VAL_INVALID_FORMAT',
  VAL_OUT_OF_RANGE = 'VAL_OUT_OF_RANGE',
  VAL_IDEMPOTENCY_KEY_MISSING = 'VAL_IDEMPOTENCY_KEY_MISSING',
  VAL_IDEMPOTENCY_KEY_PATH_MISMATCH = 'VAL_IDEMPOTENCY_KEY_PATH_MISMATCH',

  // ── Resource ──────────────────────────────────────────────────────────────
  RES_NOT_FOUND = 'RES_NOT_FOUND',
  RES_ALREADY_EXISTS = 'RES_ALREADY_EXISTS',
  RES_EMAIL_TAKEN = 'RES_EMAIL_TAKEN',
  RES_COURSE_NOT_FOUND = 'RES_COURSE_NOT_FOUND',
  RES_STUDENT_NOT_FOUND = 'RES_STUDENT_NOT_FOUND',
  RES_TUTOR_NOT_FOUND = 'RES_TUTOR_NOT_FOUND',
  RES_ORGANIZATION_NOT_FOUND = 'RES_ORGANIZATION_NOT_FOUND',
  RES_ENROLLMENT_NOT_FOUND = 'RES_ENROLLMENT_NOT_FOUND',
  RES_LOAN_NOT_FOUND = 'RES_LOAN_NOT_FOUND',
  RES_LEDGER_ENTRY_NOT_FOUND = 'RES_LEDGER_ENTRY_NOT_FOUND',
  RES_CHARGE_POLICY_NOT_FOUND = 'RES_CHARGE_POLICY_NOT_FOUND',
  RES_WAIVER_REQUEST_NOT_FOUND = 'RES_WAIVER_REQUEST_NOT_FOUND',
  RES_CERTIFICATE_NOT_FOUND = 'RES_CERTIFICATE_NOT_FOUND',
  RES_BOOK_NOT_FOUND = 'RES_BOOK_NOT_FOUND',
  RES_HOLD_NOT_FOUND = 'RES_HOLD_NOT_FOUND',
  RES_AUDIT_LOG_NOT_FOUND = 'RES_AUDIT_LOG_NOT_FOUND',
  RES_BOOK_COPY_NOT_FOUND = 'RES_BOOK_COPY_NOT_FOUND',
  RES_REMINDER_PREFERENCE_NOT_FOUND = 'RES_REMINDER_PREFERENCE_NOT_FOUND',
  RES_REMINDER_LOG_NOT_FOUND = 'RES_REMINDER_LOG_NOT_FOUND',

  // ── E-Library new entities (#1037 / #1038 / #1039) ────────────────────────
  RES_LIBRARY_CHARGE_PAYMENT_NOT_FOUND = 'RES_LIBRARY_CHARGE_PAYMENT_NOT_FOUND',
  RES_LOST_ITEM_NOT_FOUND = 'RES_LOST_ITEM_NOT_FOUND',
  RES_SUSPENSION_NOT_FOUND = 'RES_SUSPENSION_NOT_FOUND',

  // ── E-Library acquisitions / catalog (#992 / #991 / #990 / #989) ────────
  RES_ACQUISITION_ORDER_NOT_FOUND = 'RES_ACQUISITION_ORDER_NOT_FOUND',
  RES_IMPORT_JOB_NOT_FOUND = 'RES_IMPORT_JOB_NOT_FOUND',
  RES_DUPLICATE_DETECTION_FAILED = 'RES_DUPLICATE_DETECTION_FAILED',

  // ── Business rules ────────────────────────────────────────────────────────
  BIZ_ALREADY_ENROLLED = 'BIZ_ALREADY_ENROLLED',
  BIZ_COURSE_NOT_PUBLISHED = 'BIZ_COURSE_NOT_PUBLISHED',
  BIZ_INSUFFICIENT_FUNDS = 'BIZ_INSUFFICIENT_FUNDS',
  BIZ_PAYMENT_FAILED = 'BIZ_PAYMENT_FAILED',
  BIZ_REVIEW_ALREADY_SUBMITTED = 'BIZ_REVIEW_ALREADY_SUBMITTED',
  BIZ_SUBSCRIPTION_INACTIVE = 'BIZ_SUBSCRIPTION_INACTIVE',
  BIZ_FINANCIAL_AID_ALREADY_APPLIED = 'BIZ_FINANCIAL_AID_ALREADY_APPLIED',
  BIZ_SOFT_DELETED = 'BIZ_SOFT_DELETED',
  BIZ_DUPLICATE_REQUEST = 'BIZ_DUPLICATE_REQUEST',
  BIZ_ITEM_UNAVAILABLE = 'BIZ_ITEM_UNAVAILABLE',
  BIZ_LOAN_ALREADY_RETURNED = 'BIZ_LOAN_ALREADY_RETURNED',
  BIZ_RENEWAL_LIMIT_EXCEEDED = 'BIZ_RENEWAL_LIMIT_EXCEEDED',
  BIZ_OVERRIDE_REQUIRES_APPROVAL = 'BIZ_OVERRIDE_REQUIRES_APPROVAL',
  BIZ_OVERRIDE_ALREADY_RESOLVED = 'BIZ_OVERRIDE_ALREADY_RESOLVED',
  BIZ_CONTENT_REPORT_DUPLICATE = 'BIZ_CONTENT_REPORT_DUPLICATE',
  BIZ_CONTENT_REPORT_RATE_LIMITED = 'BIZ_CONTENT_REPORT_RATE_LIMITED',
  BIZ_ONE_REVIEW_PER_BOOK = 'BIZ_ONE_REVIEW_PER_BOOK',
  BIZ_PATRON_NOTE_ACCESS_DENIED = 'BIZ_PATRON_NOTE_ACCESS_DENIED',
  BIZ_PATRON_NOTE_RETENTION_EXPIRED = 'BIZ_PATRON_NOTE_RETENTION_EXPIRED',

  BIZ_NO_COPIES_AVAILABLE = 'BIZ_NO_COPIES_AVAILABLE',
  BIZ_HOLD_ALREADY_EXISTS = 'BIZ_HOLD_ALREADY_EXISTS',
  BIZ_HOLD_LIMIT_REACHED = 'BIZ_HOLD_LIMIT_REACHED',
  BIZ_BOOK_HAS_HOLDS = 'BIZ_BOOK_HAS_HOLDS',
  BIZ_LOAN_NOT_ACTIVE = 'BIZ_LOAN_NOT_ACTIVE',
  BIZ_LOAN_OVERDUE = 'BIZ_LOAN_OVERDUE',
  BIZ_RENEWAL_LIMIT_REACHED = 'BIZ_RENEWAL_LIMIT_REACHED',
  BIZ_COPY_NOT_RENEWABLE = 'BIZ_COPY_NOT_RENEWABLE',
  BIZ_DUPLICATE_EDITION_HOLD = 'BIZ_DUPLICATE_EDITION_HOLD',
  BIZ_NO_EFFECTIVE_POLICY = 'BIZ_NO_EFFECTIVE_POLICY',

  // ── E-Library charge payments (#1037) ─────────────────────────────────────
  BIZ_INVALID_CHARGE_ENTRY = 'BIZ_INVALID_CHARGE_ENTRY',
  BIZ_PAYMENT_AMOUNT_EXCEEDS_CHARGE = 'BIZ_PAYMENT_AMOUNT_EXCEEDS_CHARGE',
  BIZ_PAYMENT_ALREADY_APPLIED = 'BIZ_PAYMENT_ALREADY_APPLIED',

  // ── E-Library waiver workflow (pre-existing, now explicit) ────────────────
  BIZ_WAIVER_EXCEEDS_CHARGE = 'BIZ_WAIVER_EXCEEDS_CHARGE',
  BIZ_WAIVER_ALREADY_DECIDED = 'BIZ_WAIVER_ALREADY_DECIDED',
  BIZ_WAIVER_SELF_APPROVAL = 'BIZ_WAIVER_SELF_APPROVAL',

  // ── E-Library lost items (#1038) ───────────────────────────────────────────
  BIZ_LOST_ITEM_ALREADY_DECLARED = 'BIZ_LOST_ITEM_ALREADY_DECLARED',
  BIZ_LOST_ITEM_ALREADY_PROCESSED = 'BIZ_LOST_ITEM_ALREADY_PROCESSED',

  // ── E-Library borrowing suspensions (#1039) ────────────────────────────────
  BIZ_PATRON_ALREADY_SUSPENDED = 'BIZ_PATRON_ALREADY_SUSPENDED',
  BIZ_SUSPENSION_NOT_ACTIVE = 'BIZ_SUSPENSION_NOT_ACTIVE',
  BIZ_SUSPENSION_SELF_LIFT = 'BIZ_SUSPENSION_SELF_LIFT',

  // ── E-Library import / merge / acquisition (#990 / #989 / #992) ────────────
  BIZ_IMPORT_SIZE_EXCEEDED = 'BIZ_IMPORT_SIZE_EXCEEDED',
  BIZ_IMPORT_DUPLICATE_IDEMPOTENCY_KEY = 'BIZ_IMPORT_DUPLICATE_IDEMPOTENCY_KEY',
  BIZ_MERGE_SAME_RECORD = 'BIZ_MERGE_SAME_RECORD',

  // ── System ────────────────────────────────────────────────────────────────
  SYS_INTERNAL_ERROR = 'SYS_INTERNAL_ERROR',
  SYS_SERVICE_UNAVAILABLE = 'SYS_SERVICE_UNAVAILABLE',
  SYS_RATE_LIMIT_EXCEEDED = 'SYS_RATE_LIMIT_EXCEEDED',
}
