/**
 * Machine-readable domain error codes returned in every API error response.
 *
 * Format: <DOMAIN>_<DESCRIPTION>
 *
 * Auth codes (AUTH_*)          – authentication and authorization failures
 * Validation codes (VAL_*)     – input / schema validation failures
 * Resource codes (RES_*)       – entity lookup / conflict failures
 * Business-rule codes (BIZ_*)  – domain rule violations
 * System codes (SYS_*)         – internal / infrastructure errors
 */
export enum ErrorCode {
  // ── Auth ──────────────────────────────────────────────────────────────────
  AUTH_MISSING_TOKEN = 'AUTH_MISSING_TOKEN',
  AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN',
  AUTH_EXPIRED_TOKEN = 'AUTH_EXPIRED_TOKEN',
  AUTH_REFRESH_TOKEN_INVALID = 'AUTH_REFRESH_TOKEN_INVALID',
  AUTH_REFRESH_TOKEN_EXPIRED = 'AUTH_REFRESH_TOKEN_EXPIRED',
  AUTH_INSUFFICIENT_PERMISSIONS = 'AUTH_INSUFFICIENT_PERMISSIONS',
  AUTH_ACCOUNT_NOT_VERIFIED = 'AUTH_ACCOUNT_NOT_VERIFIED',
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_DISABLED = 'AUTH_ACCOUNT_DISABLED',
  AUTH_CERTIFICATE_DOWNLOAD_TOKEN_INVALID = 'AUTH_CERTIFICATE_DOWNLOAD_TOKEN_INVALID',
  AUTH_CERTIFICATE_DOWNLOAD_TOKEN_EXPIRED = 'AUTH_CERTIFICATE_DOWNLOAD_TOKEN_EXPIRED',
  AUTH_CERTIFICATE_DOWNLOAD_TOKEN_MISMATCH = 'AUTH_CERTIFICATE_DOWNLOAD_TOKEN_MISMATCH',

  // ── Validation ────────────────────────────────────────────────────────────
  VAL_INVALID_INPUT = 'VAL_INVALID_INPUT',
  VAL_MISSING_FIELD = 'VAL_MISSING_FIELD',
  VAL_INVALID_FORMAT = 'VAL_INVALID_FORMAT',
  VAL_OUT_OF_RANGE = 'VAL_OUT_OF_RANGE',
  VAL_IDEMPOTENCY_KEY_MISSING = 'VAL_IDEMPOTENCY_KEY_MISSING',
  VAL_IDEMPOTENCY_KEY_PATH_MISMATCH = 'VAL_IDEMPOTENCY_KEY_PATH_MISMATCH',
  VAL_SEARCH_QUERY_TOO_LONG = 'VAL_SEARCH_QUERY_TOO_LONG',
  VAL_AUTOCOMPLETE_QUERY_TOO_SHORT = 'VAL_AUTOCOMPLETE_QUERY_TOO_SHORT',

  // ── Resource ──────────────────────────────────────────────────────────────
  RES_NOT_FOUND = 'RES_NOT_FOUND',
  RES_ALREADY_EXISTS = 'RES_ALREADY_EXISTS',
  RES_EMAIL_TAKEN = 'RES_EMAIL_TAKEN',
  RES_COURSE_NOT_FOUND = 'RES_COURSE_NOT_FOUND',
  RES_STUDENT_NOT_FOUND = 'RES_STUDENT_NOT_FOUND',
  RES_TUTOR_NOT_FOUND = 'RES_TUTOR_NOT_FOUND',
  RES_ORGANIZATION_NOT_FOUND = 'RES_ORGANIZATION_NOT_FOUND',
  RES_ENROLLMENT_NOT_FOUND = 'RES_ENROLLMENT_NOT_FOUND',
  RES_LOAN_NOT_FOUND = 'RES_LOAN_NOT_FOUND',
  RES_LEDGER_ENTRY_NOT_FOUND = 'RES_LEDGER_ENTRY_NOT_FOUND',
  RES_CHARGE_POLICY_NOT_FOUND = 'RES_CHARGE_POLICY_NOT_FOUND',
  RES_WAIVER_REQUEST_NOT_FOUND = 'RES_WAIVER_REQUEST_NOT_FOUND',
  RES_CERTIFICATE_NOT_FOUND = 'RES_CERTIFICATE_NOT_FOUND',
  RES_BOOK_NOT_FOUND = 'RES_BOOK_NOT_FOUND',
  RES_HOLD_NOT_FOUND = 'RES_HOLD_NOT_FOUND',
  RES_AUDIT_LOG_NOT_FOUND = 'RES_AUDIT_LOG_NOT_FOUND',
  RES_BOOK_COPY_NOT_FOUND = 'RES_BOOK_COPY_NOT_FOUND',
  RES_REMINDER_PREFERENCE_NOT_FOUND = 'RES_REMINDER_PREFERENCE_NOT_FOUND',
  RES_REMINDER_LOG_NOT_FOUND = 'RES_REMINDER_LOG_NOT_FOUND',
  RES_SERIES_NOT_FOUND = 'RES_SERIES_NOT_FOUND',
  RES_OFFLINE_GRANT_NOT_FOUND = 'RES_OFFLINE_GRANT_NOT_FOUND',
  RES_RENDITION_INTEGRITY_NOT_FOUND = 'RES_RENDITION_INTEGRITY_NOT_FOUND',
  RES_INTEGRITY_JOB_NOT_FOUND = 'RES_INTEGRITY_JOB_NOT_FOUND',
  RES_SCHOLARSHIP_PROGRAM_NOT_FOUND = 'RES_SCHOLARSHIP_PROGRAM_NOT_FOUND',
  RES_TERMS_VERSION_NOT_FOUND = 'RES_TERMS_VERSION_NOT_FOUND',
  RES_SCHOLARSHIP_APPLICATION_NOT_FOUND = 'RES_SCHOLARSHIP_APPLICATION_NOT_FOUND',

  // ── E-Library new entities (#1037 / #1038 / #1039) ────────────────────────
  RES_LIBRARY_CHARGE_PAYMENT_NOT_FOUND = 'RES_LIBRARY_CHARGE_PAYMENT_NOT_FOUND',
  RES_LOST_ITEM_NOT_FOUND = 'RES_LOST_ITEM_NOT_FOUND',
  RES_SUSPENSION_NOT_FOUND = 'RES_SUSPENSION_NOT_FOUND',

  // ── E-Library acquisitions / catalog (#992 / #991 / #990 / #989) ────────
  RES_ACQUISITION_ORDER_NOT_FOUND = 'RES_ACQUISITION_ORDER_NOT_FOUND',
  RES_IMPORT_JOB_NOT_FOUND = 'RES_IMPORT_JOB_NOT_FOUND',
  RES_DUPLICATE_DETECTION_FAILED = 'RES_DUPLICATE_DETECTION_FAILED',

  // ── Business rules ────────────────────────────────────────────────────────
  BIZ_ALREADY_ENROLLED = 'BIZ_ALREADY_ENROLLED',
  BIZ_COURSE_NOT_PUBLISHED = 'BIZ_COURSE_NOT_PUBLISHED',
  BIZ_INSUFFICIENT_FUNDS = 'BIZ_INSUFFICIENT_FUNDS',
  BIZ_PAYMENT_FAILED = 'BIZ_PAYMENT_FAILED',
  BIZ_REVIEW_ALREADY_SUBMITTED = 'BIZ_REVIEW_ALREADY_SUBMITTED',
  BIZ_SUBSCRIPTION_INACTIVE = 'BIZ_SUBSCRIPTION_INACTIVE',
  BIZ_FINANCIAL_AID_ALREADY_APPLIED = 'BIZ_FINANCIAL_AID_ALREADY_APPLIED',
  BIZ_SOFT_DELETED = 'BIZ_SOFT_DELETED',
  BIZ_DUPLICATE_REQUEST = 'BIZ_DUPLICATE_REQUEST',
  BIZ_SCHOLARSHIP_SCHEDULE_INVALID = 'BIZ_SCHOLARSHIP_SCHEDULE_INVALID',
  BIZ_SCHOLARSHIP_SCHEDULE_IMMUTABLE = 'BIZ_SCHOLARSHIP_SCHEDULE_IMMUTABLE',
  BIZ_SCHOLARSHIP_AMENDMENT_INVALID = 'BIZ_SCHOLARSHIP_AMENDMENT_INVALID',
  BIZ_SCHOLARSHIP_MILESTONE_NOT_ACTIVE = 'BIZ_SCHOLARSHIP_MILESTONE_NOT_ACTIVE',
  BIZ_SCHOLARSHIP_EVIDENCE_KEY_REUSED = 'BIZ_SCHOLARSHIP_EVIDENCE_KEY_REUSED',
  BIZ_SCHOLARSHIP_EVIDENCE_STALE = 'BIZ_SCHOLARSHIP_EVIDENCE_STALE',
  BIZ_SCHOLARSHIP_VERIFIER_CONFLICT = 'BIZ_SCHOLARSHIP_VERIFIER_CONFLICT',
  BIZ_SCHOLARSHIP_VERIFIER_NOT_ASSIGNED = 'BIZ_SCHOLARSHIP_VERIFIER_NOT_ASSIGNED',
  BIZ_SCHOLARSHIP_REASON_CODE_MISMATCH = 'BIZ_SCHOLARSHIP_REASON_CODE_MISMATCH',
  BIZ_SCHOLARSHIP_ALREADY_DECIDED = 'BIZ_SCHOLARSHIP_ALREADY_DECIDED',
  BIZ_SCHOLARSHIP_INTENT_INTEGRITY = 'BIZ_SCHOLARSHIP_INTENT_INTEGRITY',
  BIZ_SCHOLARSHIP_INTENT_TRANSITION = 'BIZ_SCHOLARSHIP_INTENT_TRANSITION',
  BIZ_INVALID_STATE_TRANSITION = 'BIZ_INVALID_STATE_TRANSITION',
  BIZ_SEPARATION_OF_DUTIES = 'BIZ_SEPARATION_OF_DUTIES',
  BIZ_ASSET_MISMATCH = 'BIZ_ASSET_MISMATCH',
  BIZ_DEPOSIT_ALREADY_RECORDED = 'BIZ_DEPOSIT_ALREADY_RECORDED',
  BIZ_FEE_EXCEEDS_AMOUNT = 'BIZ_FEE_EXCEEDS_AMOUNT',
  BIZ_AMOUNT_EXCEEDS_OUTSTANDING = 'BIZ_AMOUNT_EXCEEDS_OUTSTANDING',
  BIZ_FUNDING_ROUND_CLOSED = 'BIZ_FUNDING_ROUND_CLOSED',
  BIZ_ITEM_UNAVAILABLE = 'BIZ_ITEM_UNAVAILABLE',
  BIZ_LOAN_ALREADY_RETURNED = 'BIZ_LOAN_ALREADY_RETURNED',
  BIZ_RENEWAL_LIMIT_EXCEEDED = 'BIZ_RENEWAL_LIMIT_EXCEEDED',
  BIZ_OVERRIDE_REQUIRES_APPROVAL = 'BIZ_OVERRIDE_REQUIRES_APPROVAL',
  BIZ_OVERRIDE_ALREADY_RESOLVED = 'BIZ_OVERRIDE_ALREADY_RESOLVED',
  BIZ_CONTENT_REPORT_DUPLICATE = 'BIZ_CONTENT_REPORT_DUPLICATE',
  BIZ_CONTENT_REPORT_RATE_LIMITED = 'BIZ_CONTENT_REPORT_RATE_LIMITED',
  BIZ_ONE_REVIEW_PER_BOOK = 'BIZ_ONE_REVIEW_PER_BOOK',
  BIZ_PATRON_NOTE_ACCESS_DENIED = 'BIZ_PATRON_NOTE_ACCESS_DENIED',
  BIZ_PATRON_NOTE_RETENTION_EXPIRED = 'BIZ_PATRON_NOTE_RETENTION_EXPIRED',

  BIZ_NO_COPIES_AVAILABLE = 'BIZ_NO_COPIES_AVAILABLE',
  BIZ_HOLD_ALREADY_EXISTS = 'BIZ_HOLD_ALREADY_EXISTS',
  BIZ_HOLD_LIMIT_REACHED = 'BIZ_HOLD_LIMIT_REACHED',
  BIZ_BOOK_HAS_HOLDS = 'BIZ_BOOK_HAS_HOLDS',
  BIZ_LOAN_NOT_ACTIVE = 'BIZ_LOAN_NOT_ACTIVE',
  BIZ_LOAN_OVERDUE = 'BIZ_LOAN_OVERDUE',
  BIZ_RENEWAL_LIMIT_REACHED = 'BIZ_RENEWAL_LIMIT_REACHED',
  BIZ_COPY_NOT_RENEWABLE = 'BIZ_COPY_NOT_RENEWABLE',
  BIZ_DUPLICATE_EDITION_HOLD = 'BIZ_DUPLICATE_EDITION_HOLD',
  BIZ_NO_EFFECTIVE_POLICY = 'BIZ_NO_EFFECTIVE_POLICY',
  BIZ_INVALID_SEARCH_FIELD = 'BIZ_INVALID_SEARCH_FIELD',

  // ── E-Library charge payments (#1037) ─────────────────────────────────────
  BIZ_INVALID_CHARGE_ENTRY = 'BIZ_INVALID_CHARGE_ENTRY',
  BIZ_PAYMENT_AMOUNT_EXCEEDS_CHARGE = 'BIZ_PAYMENT_AMOUNT_EXCEEDS_CHARGE',
  BIZ_PAYMENT_ALREADY_APPLIED = 'BIZ_PAYMENT_ALREADY_APPLIED',

  // ── E-Library waiver workflow (pre-existing, now explicit) ────────────────
  BIZ_WAIVER_EXCEEDS_CHARGE = 'BIZ_WAIVER_EXCEEDS_CHARGE',
  BIZ_WAIVER_ALREADY_DECIDED = 'BIZ_WAIVER_ALREADY_DECIDED',
  BIZ_WAIVER_SELF_APPROVAL = 'BIZ_WAIVER_SELF_APPROVAL',

  // ── E-Library lost items (#1038) ───────────────────────────────────────────
  BIZ_LOST_ITEM_ALREADY_DECLARED = 'BIZ_LOST_ITEM_ALREADY_DECLARED',
  BIZ_LOST_ITEM_ALREADY_PROCESSED = 'BIZ_LOST_ITEM_ALREADY_PROCESSED',

  // ── E-Library borrowing suspensions (#1039) ────────────────────────────────
  BIZ_PATRON_ALREADY_SUSPENDED = 'BIZ_PATRON_ALREADY_SUSPENDED',
  BIZ_SUSPENSION_NOT_ACTIVE = 'BIZ_SUSPENSION_NOT_ACTIVE',
  BIZ_SUSPENSION_SELF_LIFT = 'BIZ_SUSPENSION_SELF_LIFT',

  // ── E-Library recommendations (defaults) ───────────────────────────────────
  BIZ_BOOK_ALREADY_IN_SERIES = 'BIZ_BOOK_ALREADY_IN_SERIES',
  BIZ_USER_OPTED_OUT_RECOMMENDATIONS = 'BIZ_USER_OPTED_OUT_RECOMMENDATIONS',
  // ── E-Library import / merge / acquisition (#990 / #989 / #992) ────────────
  BIZ_IMPORT_SIZE_EXCEEDED = 'BIZ_IMPORT_SIZE_EXCEEDED',
  BIZ_IMPORT_DUPLICATE_IDEMPOTENCY_KEY = 'BIZ_IMPORT_DUPLICATE_IDEMPOTENCY_KEY',
  BIZ_MERGE_SAME_RECORD = 'BIZ_MERGE_SAME_RECORD',
  // ── E-Library offline downloads (#1045) ───────────────────────────────────
  BIZ_LOAN_EXPIRED = 'BIZ_LOAN_EXPIRED',
  BIZ_OFFLINE_DEVICE_LIMIT = 'BIZ_OFFLINE_DEVICE_LIMIT',
  BIZ_OFFLINE_GRANT_INACTIVE = 'BIZ_OFFLINE_GRANT_INACTIVE',
  BIZ_OFFLINE_DOWNLOAD_DENIED = 'BIZ_OFFLINE_DOWNLOAD_DENIED',
  // ── E-Library file integrity (#1047) ──────────────────────────────────────
  BIZ_RENDITION_ALREADY_REGISTERED = 'BIZ_RENDITION_ALREADY_REGISTERED',
  BIZ_RENDITION_ALREADY_QUARANTINED = 'BIZ_RENDITION_ALREADY_QUARANTINED',
  BIZ_RENDITION_NOT_QUARANTINED = 'BIZ_RENDITION_NOT_QUARANTINED',
  BIZ_RENDITION_QUARANTINED = 'BIZ_RENDITION_QUARANTINED',
  // ── Scholarships: versioned program terms (#1126) ─────────────────────────
  BIZ_TERMS_VERSION_NOT_DRAFT = 'BIZ_TERMS_VERSION_NOT_DRAFT',
  BIZ_TERMS_VERSION_NOT_PUBLISHED = 'BIZ_TERMS_VERSION_NOT_PUBLISHED',
  BIZ_PROGRAM_NOT_OPEN = 'BIZ_PROGRAM_NOT_OPEN',
  BIZ_APPLICATION_ALREADY_EXISTS = 'BIZ_APPLICATION_ALREADY_EXISTS',
  BIZ_APPLICATION_NOT_REVIEWABLE = 'BIZ_APPLICATION_NOT_REVIEWABLE',
  BIZ_APPLICATION_NOT_WITHDRAWABLE = 'BIZ_APPLICATION_NOT_WITHDRAWABLE',

  // ── Scholarships: answer validation (#1132) ────────────────────────────────
  /** One or more application answers failed word-limit or required-field rules. */
  VAL_ANSWER_WORD_LIMIT_EXCEEDED = 'VAL_ANSWER_WORD_LIMIT_EXCEEDED',
  /** An answer references a field id that does not exist on the program form. */
  VAL_ANSWER_UNKNOWN_FIELD = 'VAL_ANSWER_UNKNOWN_FIELD',
  /** A required form field was not answered. */
  VAL_ANSWER_REQUIRED_FIELD_MISSING = 'VAL_ANSWER_REQUIRED_FIELD_MISSING',
  /** The answers array contains duplicate field ids. */
  VAL_ANSWER_DUPLICATE_FIELD = 'VAL_ANSWER_DUPLICATE_FIELD',

  // ── Scholarships: program lifecycle states (#1122) ────────────────────────
  /** The requested status transition is not permitted. */
  BIZ_PROGRAM_INVALID_TRANSITION = 'BIZ_PROGRAM_INVALID_TRANSITION',
  /** Archived programs cannot be modified. */
  BIZ_PROGRAM_ARCHIVED = 'BIZ_PROGRAM_ARCHIVED',

  // ── Scholarships: withdrawal policy (#1137) ───────────────────────────────
  /** Self-withdrawal is disabled by the program's withdrawal policy. */
  BIZ_WITHDRAWAL_NOT_ALLOWED = 'BIZ_WITHDRAWAL_NOT_ALLOWED',
  /** The withdrawal window (hours after submission) has elapsed. */
  BIZ_WITHDRAWAL_WINDOW_EXPIRED = 'BIZ_WITHDRAWAL_WINDOW_EXPIRED',
  /** Approved applications cannot be withdrawn. */
  BIZ_APPROVED_APPLICATION_NOT_WITHDRAWABLE = 'BIZ_APPROVED_APPLICATION_NOT_WITHDRAWABLE',
  /** No withdrawal policy document found. */
  RES_WITHDRAWAL_POLICY_NOT_FOUND = 'RES_WITHDRAWAL_POLICY_NOT_FOUND',

  // ── Scholarships: composable eligibility rules (#1127) ────────────────────
  /** An eligibility rule of this type already exists for the program. */
  BIZ_ELIGIBILITY_RULE_CONFLICT = 'BIZ_ELIGIBILITY_RULE_CONFLICT',
  /** The eligibility rule was not found. */
  RES_ELIGIBILITY_RULE_NOT_FOUND = 'RES_ELIGIBILITY_RULE_NOT_FOUND',
  // ── Scholarships: prerequisite and exclusion rules (#1128) ───────────────
  RES_PROGRAM_PREREQUISITE_NOT_FOUND = 'RES_PROGRAM_PREREQUISITE_NOT_FOUND',
  RES_PROGRAM_EXCLUSION_NOT_FOUND = 'RES_PROGRAM_EXCLUSION_NOT_FOUND',
  /** Duplicate prerequisite (same type + referenceId) for a program. */
  BIZ_PREREQUISITE_DUPLICATE = 'BIZ_PREREQUISITE_DUPLICATE',
  /** Duplicate exclusion type for a program. */
  BIZ_EXCLUSION_DUPLICATE = 'BIZ_EXCLUSION_DUPLICATE',
  /** A prerequisite creates a self-referential cycle. */
  BIZ_PREREQUISITE_CYCLE_DETECTED = 'BIZ_PREREQUISITE_CYCLE_DETECTED',
  // ── Scholarships: eligibility attestations (#1129) ───────────────────────
  RES_ELIGIBILITY_ATTESTATION_NOT_FOUND = 'RES_ELIGIBILITY_ATTESTATION_NOT_FOUND',
  /** Attestation has already been revoked. */
  BIZ_ATTESTATION_ALREADY_REVOKED = 'BIZ_ATTESTATION_ALREADY_REVOKED',
  /** Attestation has expired. */
  BIZ_ATTESTATION_EXPIRED = 'BIZ_ATTESTATION_EXPIRED',
  /** expiresAt must be a future date. */
  BIZ_ATTESTATION_INVALID_EXPIRY = 'BIZ_ATTESTATION_INVALID_EXPIRY',

  // ── E-Library reserve collection (#1052) ─────────────────────────────────
  BIZ_RESERVE_CONFLICT = 'BIZ_RESERVE_CONFLICT',
  BIZ_RESERVE_NOT_CANCELLABLE = 'BIZ_RESERVE_NOT_CANCELLABLE',
  // ── Scholarships application forms (#1131) ────────────────────────────────
  BIZ_FORM_NOT_DRAFT = 'BIZ_FORM_NOT_DRAFT',
  BIZ_FORM_NOT_PUBLISHED = 'BIZ_FORM_NOT_PUBLISHED',
  BIZ_FORM_VERSION_MISMATCH = 'BIZ_FORM_VERSION_MISMATCH',

  // ── Scholarship finance ───────────────────────────────────────────────────
  RES_SCHOLARSHIP_PROGRAM_NOT_FOUND = 'RES_SCHOLARSHIP_PROGRAM_NOT_FOUND',
  RES_LEDGER_ENTRY_NOT_FOUND = 'RES_LEDGER_ENTRY_NOT_FOUND',
  RES_PAYOUT_NOT_FOUND = 'RES_PAYOUT_NOT_FOUND',
  RES_RECEIPT_NOT_FOUND = 'RES_RECEIPT_NOT_FOUND',
  RES_RECONCILIATION_NOT_FOUND = 'RES_RECONCILIATION_NOT_FOUND',
  BIZ_LEDGER_UNBALANCED = 'BIZ_LEDGER_UNBALANCED',
  BIZ_LEDGER_REFERENCE_CONFLICT = 'BIZ_LEDGER_REFERENCE_CONFLICT',
  BIZ_LEDGER_ENTRY_ALREADY_REVERSED = 'BIZ_LEDGER_ENTRY_ALREADY_REVERSED',
  BIZ_LEDGER_BUSY = 'BIZ_LEDGER_BUSY',
  BIZ_PROGRAM_INSOLVENT = 'BIZ_PROGRAM_INSOLVENT',
  BIZ_RECONCILIATION_BLOCKED = 'BIZ_RECONCILIATION_BLOCKED',
  BIZ_PAYOUT_INVALID_STATE = 'BIZ_PAYOUT_INVALID_STATE',
  BIZ_PAYOUT_RETRY_NOT_ALLOWED = 'BIZ_PAYOUT_RETRY_NOT_ALLOWED',
  BIZ_PAYOUT_ENVELOPE_REUSED = 'BIZ_PAYOUT_ENVELOPE_REUSED',
  SYS_HORIZON_UNAVAILABLE = 'SYS_HORIZON_UNAVAILABLE',
  // ── Scholarships: normalized aggregate review scores (#1147) ──────────────
  /** Reviewer has already submitted a review for this application. */
  BIZ_REVIEW_ALREADY_EXISTS = 'BIZ_REVIEW_ALREADY_EXISTS',
  /** Application is not in a reviewable state (must be UNDER_REVIEW). */
  BIZ_APPLICATION_NOT_UNDER_REVIEW = 'BIZ_APPLICATION_NOT_UNDER_REVIEW',
  /** Review rubric criteria weights do not sum to 1.0 (within tolerance). */
  VAL_RUBRIC_WEIGHTS_INVALID = 'VAL_RUBRIC_WEIGHTS_INVALID',
  /** A rubric criterion score is outside the permitted [0, maxScore] range. */
  VAL_RUBRIC_SCORE_OUT_OF_RANGE = 'VAL_RUBRIC_SCORE_OUT_OF_RANGE',
  /** Rubric criteria array is empty — at least one criterion is required. */
  VAL_RUBRIC_CRITERIA_EMPTY = 'VAL_RUBRIC_CRITERIA_EMPTY',
  /** The requested review was not found. */
  RES_SCHOLARSHIP_REVIEW_NOT_FOUND = 'RES_SCHOLARSHIP_REVIEW_NOT_FOUND',
  /** Aggregate score cannot be computed — no completed reviews exist. */
  BIZ_NO_COMPLETED_REVIEWS = 'BIZ_NO_COMPLETED_REVIEWS',

  // ── Scholarships: reviewer info requests (#1146) ──────────────────────────
  /** The info-request document was not found. */
  RES_INFO_REQUEST_NOT_FOUND = 'RES_INFO_REQUEST_NOT_FOUND',
  /** The applicant has already responded to this request (versioned responses). */
  BIZ_INFO_REQUEST_ALREADY_RESPONDED = 'BIZ_INFO_REQUEST_ALREADY_RESPONDED',
  /** The info-request is not in a state that allows the requested transition. */
  BIZ_INFO_REQUEST_INVALID_STATE = 'BIZ_INFO_REQUEST_INVALID_STATE',
  /** The response deadline for this info-request has passed. */
  BIZ_INFO_REQUEST_DEADLINE_PASSED = 'BIZ_INFO_REQUEST_DEADLINE_PASSED',
  /** The deadline supplied is not in the future. */
  VAL_INFO_REQUEST_DEADLINE_PAST = 'VAL_INFO_REQUEST_DEADLINE_PAST',
  /** The questions array is empty — at least one question is required. */
  VAL_INFO_REQUEST_NO_QUESTIONS = 'VAL_INFO_REQUEST_NO_QUESTIONS',
  /** A response answer references a question id that does not exist on this request. */
  VAL_INFO_REQUEST_UNKNOWN_QUESTION = 'VAL_INFO_REQUEST_UNKNOWN_QUESTION',
  /** A required question was not answered. */
  VAL_INFO_REQUEST_REQUIRED_ANSWER_MISSING = 'VAL_INFO_REQUEST_REQUIRED_ANSWER_MISSING',
  /** Only the reviewer who created the request may cancel it. */
  BIZ_INFO_REQUEST_CANCEL_FORBIDDEN = 'BIZ_INFO_REQUEST_CANCEL_FORBIDDEN',

  // ── Scholarships: budget reservations (#1149) ─────────────────────────────
  /** The scholarship program budget ledger was not found. */
  RES_BUDGET_LEDGER_NOT_FOUND = 'RES_BUDGET_LEDGER_NOT_FOUND',
  /** A budget reservation with this id was not found. */
  RES_BUDGET_RESERVATION_NOT_FOUND = 'RES_BUDGET_RESERVATION_NOT_FOUND',
  /** A reservation already exists for this application; cannot create a second. */
  BIZ_RESERVATION_ALREADY_EXISTS = 'BIZ_RESERVATION_ALREADY_EXISTS',
  /** The reservation amount exceeds the program's available (unreserved) budget. */
  BIZ_BUDGET_INSUFFICIENT = 'BIZ_BUDGET_INSUFFICIENT',
  /** The reservation is not in a state that allows the requested transition. */
  BIZ_RESERVATION_INVALID_STATE = 'BIZ_RESERVATION_INVALID_STATE',
  /** The reservation has already been released and cannot be released again. */
  BIZ_RESERVATION_ALREADY_RELEASED = 'BIZ_RESERVATION_ALREADY_RELEASED',
  /** The reservation has already been confirmed and cannot be cancelled. */
  BIZ_RESERVATION_ALREADY_CONFIRMED = 'BIZ_RESERVATION_ALREADY_CONFIRMED',
  /** expiresAt must be a future date. */
  VAL_RESERVATION_INVALID_EXPIRY = 'VAL_RESERVATION_INVALID_EXPIRY',
  /** totalBudget must be ≥ 0. */
  VAL_BUDGET_AMOUNT_INVALID = 'VAL_BUDGET_AMOUNT_INVALID',

  // ── System ────────────────────────────────────────────────────────────────
  SYS_INTERNAL_ERROR = 'SYS_INTERNAL_ERROR',
  SYS_SERVICE_UNAVAILABLE = 'SYS_SERVICE_UNAVAILABLE',
  SYS_RATE_LIMIT_EXCEEDED = 'SYS_RATE_LIMIT_EXCEEDED',
}
